services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  storage:
    build: .
    container_name: storage
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongo-data:
